
export const CONSTANTS = {
  PRECIO_MELAMINA_M2: 35,
  PRECIO_MELAMINA_DISENO_M2: 55,
  RECARGO_RH_BLANCO: 0.50,
  RECARGO_RH_DISENO: 0.20,
  PRECIO_CANTO_ML: 6,
  BISAGRA_STANDARD: 3.5,
  BISAGRA_CIERRE_SUAVE: 7.5,
  CORREDERA_STANDARD: 12,
  CORREDERA_CIERRE_SUAVE: 20,
  CORREDERA_PUSH_OPEN: 19,
  TIRADOR_BARRA: 7,
  TIRADOR_BOTON: 6,
  TIRADOR_PUSH_OPEN: 9,
  TIRADOR_OCULTO: 12,
  PRECIO_LED_ML: 80,
  PESO_KG_M2: 11.5,
  // Accesorios por material
  CANASTILLA_CROMADO: 90,
  CANASTILLA_INOX: 140,
  CONDIMENTERO_CROMADO: 100,
  CONDIMENTERO_INOX: 160,
  ESCURRIDOR_CROMADO: 50,
  ESCURRIDOR_INOX: 75,
  // Recargos al total del proyecto
  RECARGO_URGENCIA: 0.15,
  TRABAJO_ALTURA_FIJO: 80,
};

export const PRECIO_ACCESORIO = {
  canastillas: {
    Cromado: CONSTANTS.CANASTILLA_CROMADO,
    "Acero Inoxidable": CONSTANTS.CANASTILLA_INOX,
  },
  condimentero: {
    Cromado: CONSTANTS.CONDIMENTERO_CROMADO,
    "Acero Inoxidable": CONSTANTS.CONDIMENTERO_INOX,
  },
  escurridor: {
    Cromado: CONSTANTS.ESCURRIDOR_CROMADO,
    "Acero Inoxidable": CONSTANTS.ESCURRIDOR_INOX,
  },
};

